<?php
namespace App\Services;

use App\Core\Database;

class ExportBuilder
{
    public static function preview(?int $batchId = null, ?string $branch = null): array
    {
        $data = self::buildData($batchId, $branch);

        return [
            'categories' => count($data['categories']),
            'sites' => count($data['sites']),
        ];
    }

    public static function generate(?int $batchId = null, ?string $branch = null): array
    {
        $config = require __DIR__ . '/../../config/config.php';
        $data = self::buildData($batchId, $branch);

        $filename = 'curlie_export_' . date('Ymd_His') . '.sql';
        $fullPath = rtrim($config['paths']['exports'], DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $filename;

        $fh = fopen($fullPath, 'wb');
        if (!$fh) {
            throw new \RuntimeException('Failed to create export file: ' . $fullPath);
        }

        fwrite($fh, "-- Curlie importer export\n");
        fwrite($fh, "-- Generated at " . date('Y-m-d H:i:s') . "\n");
        fwrite($fh, "-- Filters: batch_id=" . ($batchId ?? 'all') . ", branch=" . ($branch ?: 'all') . "\n");
        fwrite($fh, "-- Categories: " . count($data['categories']) . "\n");
        fwrite($fh, "-- Sites: " . count($data['sites']) . "\n\n");

        fwrite($fh, "START TRANSACTION;\n\n");

        fwrite($fh, "-- Create live import batch record\n");
        fwrite($fh, "INSERT INTO import_batches (source_name, source_version, batch_label, notes, status, total_categories, total_sites, started_at, completed_at)\n");
        fwrite($fh, "VALUES ('curlie', NULL, " . self::sql('Curlie export ' . date('Y-m-d H:i:s')) . ", " . self::sql('Generated by standalone Curlie importer') . ", 'completed', " . count($data['categories']) . ", " . count($data['sites']) . ", NOW(), NOW());\n");
        fwrite($fh, "SET @import_batch_id = LAST_INSERT_ID();\n\n");

        fwrite($fh, "-- Categories\n");
        foreach ($data['categories'] as $category) {
            $pathSql = self::sql($category['path']);
            $parentIdExpr = 'NULL';
            if (!empty($category['parent_path'])) {
                $parentIdExpr = '(SELECT id FROM categories WHERE path = ' . self::sql($category['parent_path']) . ' LIMIT 1)';
            }

            fwrite($fh, "INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)\n");
            fwrite($fh, "SELECT {$parentIdExpr}, " .
                self::sql($category['slug']) . ", " .
                $pathSql . ", " .
                self::sql($category['name']) . ", " .
                self::sql($category['description']) . ", 0, 1, 'dmoz_import', " .
                self::sql($category['source_key']) . ", @import_batch_id, NOW(), NOW()\n");
            fwrite($fh, "WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = {$pathSql} LIMIT 1);\n\n");
        }

        fwrite($fh, "-- Sites\n");
        foreach ($data['sites'] as $site) {
            $normalized = $site['normalized_url'] ?: $site['url'];
            $categoryPathSql = self::sql($site['category_path']);
            $normalizedSql = self::sql($normalized);

            fwrite($fh, "INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)\n");
            fwrite($fh, "SELECT " .
                "(SELECT id FROM categories WHERE path = {$categoryPathSql} LIMIT 1), " .
                self::sql($site['title']) . ", " .
                self::sql($site['slug']) . ", " .
                self::sql($site['url']) . ", " .
                $normalizedSql . ", " .
                self::sql($site['description']) . ", NULL, NULL, 'active', 'dmoz_import', " .
                self::sql($site['source_key']) . ", " .
                self::sql($site['title']) . ", " .
                self::sql($site['description']) . ", " .
                self::sql($site['url']) . ", @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()\n");
            fwrite($fh, "WHERE EXISTS (SELECT 1 FROM categories WHERE path = {$categoryPathSql} LIMIT 1)\n");
            fwrite($fh, "  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = {$normalizedSql} LIMIT 1);\n\n");
        }

        fwrite($fh, "COMMIT;\n");
        fclose($fh);

        return [
            'batch_id' => $batchId,
            'filename' => $filename,
            'full_path' => $fullPath,
            'categories_count' => count($data['categories']),
            'sites_count' => count($data['sites']),
        ];
    }

    public static function writeSql(?int $batchId = null, ?string $branch = null): array
    {
        return self::generate($batchId, $branch);
    }

    private static function buildData(?int $batchId, ?string $branch): array
    {
        $pdo = Database::connection();

        [$categoryWhere, $categoryParams] = self::buildCategoryFilters($batchId, $branch);
        $categorySql = "
            SELECT
                sc.source_category_id,
                sc.category_name,
                sc.description_raw,
                sc.local_path_candidate AS source_local_path_candidate,
                cm.local_path_candidate AS mapping_local_path_candidate,
                cm.local_path_final
            FROM source_categories sc
            LEFT JOIN category_mapping cm
                ON cm.source_category_id = sc.source_category_id
            {$categoryWhere}
              AND sc.mapping_status = 'approved'
            ORDER BY sc.path_depth ASC, sc.full_path ASC
        ";

        $stmt = $pdo->prepare($categorySql);
        $stmt->execute($categoryParams);
        $categoryRows = $stmt->fetchAll();

        $categoriesByPath = [];

        foreach ($categoryRows as $row) {
            $exportPath = self::normalizePath(
                $row['local_path_final']
                ?: $row['mapping_local_path_candidate']
                ?: $row['source_local_path_candidate']
            );

            if ($exportPath === '') {
                continue;
            }

            $segments = explode('/', $exportPath);
            $build = [];

            foreach ($segments as $index => $segment) {
                $build[] = $segment;
                $path = implode('/', $build);

                if (!isset($categoriesByPath[$path])) {
                    $categoriesByPath[$path] = [
                        'path' => $path,
                        'parent_path' => $index > 0 ? implode('/', array_slice($build, 0, -1)) : null,
                        'slug' => self::slugify($segment),
                        'name' => self::titleize($segment),
                        'description' => null,
                        'source_key' => null,
                        'depth' => $index + 1,
                    ];
                }
            }

            $categoriesByPath[$exportPath]['name'] = trim((string) $row['category_name']) !== ''
                ? trim((string) $row['category_name'])
                : $categoriesByPath[$exportPath]['name'];
            $categoriesByPath[$exportPath]['description'] = $row['description_raw'];
            $categoriesByPath[$exportPath]['source_key'] = (string) $row['source_category_id'];
        }

        uasort($categoriesByPath, function (array $a, array $b): int {
            if ($a['depth'] === $b['depth']) {
                return strcmp($a['path'], $b['path']);
            }
            return $a['depth'] <=> $b['depth'];
        });

        [$siteWhere, $siteParams] = self::buildSiteFilters($batchId, $branch);
        $siteSql = "
            SELECT
                ss.id,
                ss.source_category_id,
                ss.url,
                ss.normalized_url,
                ss.title,
                ss.description_raw,
                sc.local_path_candidate AS source_local_path_candidate,
                cm.local_path_candidate AS mapping_local_path_candidate,
                cm.local_path_final
            FROM source_sites ss
            INNER JOIN source_categories sc
                ON sc.id = ss.source_category_row_id
            LEFT JOIN category_mapping cm
                ON cm.source_category_id = ss.source_category_id
            {$siteWhere}
              AND ss.import_status = 'approved'
              AND ss.duplicate_flag = 0
              AND ss.source_category_row_id IS NOT NULL
              AND sc.mapping_status = 'approved'
            ORDER BY ss.id ASC
        ";

        $stmt = $pdo->prepare($siteSql);
        $stmt->execute($siteParams);
        $siteRows = $stmt->fetchAll();

        $sites = [];
        $seenNormalized = [];

        foreach ($siteRows as $row) {
            $categoryPath = self::normalizePath(
                $row['local_path_final']
                ?: $row['mapping_local_path_candidate']
                ?: $row['source_local_path_candidate']
            );

            if ($categoryPath === '' || !isset($categoriesByPath[$categoryPath])) {
                continue;
            }

            $normalizedUrl = trim((string) ($row['normalized_url'] ?? ''));
            if ($normalizedUrl === '') {
                $normalizedUrl = trim((string) $row['url']);
            }

            if ($normalizedUrl !== '' && isset($seenNormalized[$normalizedUrl])) {
                continue;
            }
            $seenNormalized[$normalizedUrl] = true;

            $slug = self::slugify((string) $row['title']);
            if ($slug === '') {
                $slug = 'site-' . (int) $row['id'];
            }

            $sites[] = [
                'id' => (int) $row['id'],
                'category_path' => $categoryPath,
                'title' => (string) $row['title'],
                'slug' => $slug,
                'url' => (string) $row['url'],
                'normalized_url' => $normalizedUrl,
                'description' => $row['description_raw'],
                'source_key' => 'curlie:' . (string) $row['source_category_id'] . ':' . (int) $row['id'],
            ];
        }

        return [
            'categories' => array_values($categoriesByPath),
            'sites' => $sites,
        ];
    }

    private static function buildCategoryFilters(?int $batchId, ?string $branch): array
    {
        $clauses = ['WHERE 1=1'];
        $params = [];

        if ($batchId !== null) {
            $clauses[] = 'AND sc.batch_id = :batch_id';
            $params['batch_id'] = $batchId;
        }

        if ($branch !== null && $branch !== '') {
            $clauses[] = 'AND sc.top_branch = :branch';
            $params['branch'] = $branch;
        }

        return [implode(' ', $clauses), $params];
    }

    private static function buildSiteFilters(?int $batchId, ?string $branch): array
    {
        $clauses = ['WHERE 1=1'];
        $params = [];

        if ($batchId !== null) {
            $clauses[] = 'AND ss.batch_id = :batch_id';
            $params['batch_id'] = $batchId;
        }

        if ($branch !== null && $branch !== '') {
            $clauses[] = 'AND sc.top_branch = :branch';
            $params['branch'] = $branch;
        }

        return [implode(' ', $clauses), $params];
    }

    private static function normalizePath(?string $path): string
    {
        $path = trim((string) $path);
        $path = trim($path, '/');
        $path = preg_replace('#/+#', '/', $path);
        return strtolower((string) $path);
    }

    private static function slugify(?string $value): string
    {
        $value = strtolower(trim((string) $value));
        $value = preg_replace('/[^a-z0-9]+/i', '-', $value);
        $value = trim((string) $value, '-');
        return $value;
    }

    private static function titleize(string $value): string
    {
        return ucwords(str_replace(['-', '_'], ' ', $value));
    }

    private static function sql($value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        return Database::connection()->quote((string) $value);
    }
}
