-- Curlie importer export
-- Generated at 2026-03-22 20:30:05
-- Filters: batch_id=all, branch=all
-- Export Summary
-- Categories: 53
-- Sites: 10
-- Leaf categories:
--   society
--   society/death
--   society/ethnicity
--   society/genealogy
--   society/history
--   society/issues
--   society/law
--   society/organizations
--   society/people
--   society/philanthropy
--   society/philosophy
--   society/religion-and-spirituality
--   society/genealogy/surnames
--   society/history/by-region
--   society/history/by-time-period
--   society/issues/warfare-and-conflict
--   society/law/services
--   society/organizations/fraternal
--   society/people/personal-homepages
--   society/people/women
--   society/philosophy/philosophers
--   society/religion-and-spirituality/christianity
--   society/religion-and-spirituality/judaism
--   society/history/by-region/north-america
--   society/issues/warfare-and-conflict/specific-conflicts
--   society/law/services/lawyers-and-law-firms
--   society/organizations/fraternal/freemasonry
--   society/religion-and-spirituality/christianity/denominations
--   society/religion-and-spirituality/christianity/people
--   society/history/by-region/north-america/united-states
--   society/law/services/lawyers-and-law-firms/general-practice
--   society/religion-and-spirituality/christianity/denominations/anglican
--   society/religion-and-spirituality/christianity/denominations/baptist
--   society/religion-and-spirituality/christianity/denominations/catholicism
--   society/religion-and-spirituality/christianity/denominations/lutheran
--   society/religion-and-spirituality/christianity/denominations/methodist
--   society/religion-and-spirituality/christianity/denominations/presbyterian
--   society/religion-and-spirituality/christianity/people/saints
--   society/law/services/lawyers-and-law-firms/general-practice/north-america
--   society/religion-and-spirituality/christianity/denominations/baptist/baptist-groups
--   society/religion-and-spirituality/christianity/denominations/catholicism/parishes
--   society/religion-and-spirituality/christianity/denominations/catholicism/saints
--   society/religion-and-spirituality/christianity/denominations/lutheran/congregations
--   society/religion-and-spirituality/christianity/denominations/methodist/united-methodist
--   society/religion-and-spirituality/christianity/denominations/presbyterian/presbyterian-church-usa
--   society/law/services/lawyers-and-law-firms/general-practice/north-america/united-states
--   society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america
--   society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps
--   society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches
--   society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america/united-states
--   society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches/united-states

START TRANSACTION;

-- Create live import batch record
INSERT INTO import_batches (source_name, source_version, batch_label, notes, status, total_categories, total_sites, started_at, completed_at)
VALUES ('curlie', NULL, 'Curlie export 2026-03-22 20:30:05', 'Generated by standalone Curlie importer', 'completed', 53, 10, NOW(), NOW());
SET @import_batch_id = LAST_INSERT_ID();

-- Categories
INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT NULL, 'society', 'society', 'Society', 'The Society section covers the areas of human interaction and people\'s thoughts, speculations, and aspirations about the world in which they live.  It includes topics directly about people, experiences inherent to being human, people\'s relationships with each other, and people\'s perceptions and understandings of the universe. ', 0, 1, 'dmoz_import', '969617', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'death', 'society/death', 'Death', 'Sites related to the issues surrounding Death and Dying.   ', 0, 1, 'dmoz_import', '976357', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/death' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'ethnicity', 'society/ethnicity', 'Ethnicity', '<p>This section offers categories organized by their focus on specific racial and ethnic groups. Please take the time to locate the most appropriate subcategory prior to suggesting a site. An <strong><em>Ethnic Group</em></strong> is a category or group of people considered to be significantly different  from others in terms of cultural (dialect, religion, traditions, etc.)  and sometimes physical characteristics (skin color, body shape, etc.). </p> ', 0, 1, 'dmoz_import', '996568', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/ethnicity' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'genealogy', 'society/genealogy', 'Genealogy', 'This category contains sites concerning genealogy and the study of family histories, including specific family surnames and genealogy related to specific geographical areas. ', 0, 1, 'dmoz_import', '997720', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/genealogy' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'history', 'society/history', 'History', 'History, in brief, is the humanity which explains the human condition based on the chronological record of significant events and their related causes. ', 0, 1, 'dmoz_import', '970588', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/history' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'issues', 'society/issues', 'Issues', 'This category links to sites dealing with every kind of social and political issue and controversy. ', 0, 1, 'dmoz_import', '982665', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/issues' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'law', 'society/law', 'Law', 'This category is a resource for law-related websites, including law firms, legal information, primary legal materials, paralegal services, legal publications and technology, expert witnesses, litigation consultants, and other legal service providers.   ', 0, 1, 'dmoz_import', '973250', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/law' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'organizations', 'society/organizations', 'Organizations', 'English language web sites of non-profit and non-governmental organizations, as well as links to other directory categories for organizations and clubs <strong>not</strong> of a business or governmental nature.   The first grouping of subcategories including resources for the non-profit sector. The second grouping holds sites and links to organization categories in other parts of the directory. ', 0, 1, 'dmoz_import', '979619', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/organizations' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'people', 'society/people', 'People', 'People in their many shapes, sizes, and appearances. ', 0, 1, 'dmoz_import', '976911', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/people' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'philanthropy', 'society/philanthropy', 'Philanthropy', 'Broadly defined, philanthropy is goodwill to mankind as demonstrated by the readiness to promote human welfare. The Philanthropy category in this directory provides an overview of the philanthropic sector, including guides and directories and methods of giving. ', 0, 1, 'dmoz_import', '978395', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/philanthropy' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'philosophy', 'society/philosophy', 'Philosophy', 'Philosophy, from the Greek words philo (love) and sophia (wisdom), refers to the rational inquiry of the truths and principles of being, knowledge, and conduct.  Its traditional main branches are metaphysics, the study of the ultimate nature of reality, epistemology, the investigation of the origins and limits of knowledge, ethics, dealing with morality and justice, and aesthetics, the study of beauty in the arts. ', 0, 1, 'dmoz_import', '981724', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/philosophy' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'religion-and-spirituality', 'society/religion-and-spirituality', 'Religion_and_Spirituality', 'Religion is a social phenomenon involving systems of shared practices, views, symbols, and moral values. Spirituality focuses on personal connections perceived non-physical phenomena, with or without the direct influence of a religion or a set of organizationally imposed views. Please see the <A HREF=/Society/Religion_and_Spirituality/faq.html>category FAQ</A> for more detail on the category and editing in it. ', 0, 1, 'dmoz_import', '984968', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/genealogy' LIMIT 1), 'surnames', 'society/genealogy/surnames', 'Surnames', '<P><font size=\"2\" face=\"Verdana\">Sites in which the primary focus is the history of a surname or a family history connected to a specific surname.</font> ', 0, 1, 'dmoz_import', '997795', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/genealogy/surnames' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/history' LIMIT 1), 'by-region', 'society/history/by-region', 'By_Region', ' ', 0, 1, 'dmoz_import', '971480', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/history/by-region' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/history' LIMIT 1), 'by-time-period', 'society/history/by-time-period', 'By_Time_Period', 'This category lists sites devoted to history from the dawn of civilization in the ancient world to the present according to their chronological events by time periods.   ', 0, 1, 'dmoz_import', '970959', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/history/by-time-period' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/issues' LIMIT 1), 'warfare-and-conflict', 'society/issues/warfare-and-conflict', 'Warfare_and_Conflict', 'This category is for sites on warfare and conflict, including its means, effects, strategies, weapons, and consequences. ', 0, 1, 'dmoz_import', '983444', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/issues/warfare-and-conflict' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/law' LIMIT 1), 'services', 'society/law/services', 'Services', 'Consultants and service providers, providing services to legal professionals.   ', 0, 1, 'dmoz_import', '973251', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/law/services' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/organizations' LIMIT 1), 'fraternal', 'society/organizations/fraternal', 'Fraternal', 'Fraternal organizations identify themselves as brotherhoods and/or sisterhoods, with lifetime memberships, shared ideals and principles, and ritualistic traditions. These organizations may be formed with different purposes, including social interaction, public service, or mutual benefit (such as financial services or insurance for members). ', 0, 1, 'dmoz_import', '979741', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/organizations/fraternal' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/people' LIMIT 1), 'personal-homepages', 'society/people/personal-homepages', 'Personal_Homepages', '<i><b><font color=\"#0099CC\">Would you like to become an editor of Personal Homepages? We\'re looking for volunteers who are eager to contribute to this rapidly growing category of the Open Directory Project. Please sign up for a letter of the alphabet and contribute!</font></b></i>  <p>Guidelines For Submitting Sites Into Society: People: Personal Homepages </p> <p><b>We list web sites by the first letter of your last name or the first letter of your handle/screen name. For example, if your name is Jane Doe, you would submit your site to the \"D\" category because your last name begins with the letter \"D\". ONLY personal homepages belong here. Please submit your web site to the appropriate sub-category! </b></p> <blockquote> <p><b>The Title</b> <br> Should be your name, handle or screen name<br> Do not type in all caps <br> Do not include a list of keywords </p> <p>  <b>The Description</b> <br> Should be in English and in sentence form <br> A Maximum of 30 words <br> Do not submit your web site\'s history, it is not relevant <br> Do not submit a list of keywords <br> Do not use caps <br> Do not include HTML tags </p> </blockquote> <p>Your site will be reviewed by an editor at which time they will determine whether it belongs in the category you submitted it to. <b>Due to the high number of submissions to this category if you submit to the wrong place, an editor may not take the time to relocate it to a more appropriate one.</b></p> <p>Note: The Open Directory Project is not like other directories or search engines. Our goal is to provide visitors with high quality web sites, not necessarily a high quantity. <b>If your web site does not meet our basic standards it will not be entered into the directory.</b></p> ', 0, 1, 'dmoz_import', '976916', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/people/personal-homepages' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/people' LIMIT 1), 'women', 'society/people/women', 'Women', 'Resources for women, about women, and most often provided by women. Women in business, women\'s groups, clubs and societies, women who want to chat, women\'s email lists and magazines, women\'s spirituality and issues and culture are found here. Also resources for wives, mothers, widows and every woman in between. ', 0, 1, 'dmoz_import', '977662', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/people/women' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/philosophy' LIMIT 1), 'philosophers', 'society/philosophy/philosophers', 'Philosophers', 'This category includes sites with philosophers as their subject.  Content may include biographical and bibliographical information, articles, interviews, electronic texts, mailing lists, and secondary literature. ', 0, 1, 'dmoz_import', '981934', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/philosophy/philosophers' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality' LIMIT 1), 'christianity', 'society/religion-and-spirituality/christianity', 'Christianity', 'This category includes sites that relate to Christianity, Christ, the Bible, Christian lifestyle and the Church. ', 0, 1, 'dmoz_import', '987953', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality' LIMIT 1), 'judaism', 'society/religion-and-spirituality/judaism', 'Judaism', 'Religious culture of the Jews, one of the world\'s oldest religious traditions. Premodern Judaism constituted (and traditional Judaism today constitutes) an integrated cultural system of Jewish law, custom, and practice encompassing the totality of individual and communal existence. It is a system of sanctification in which all is to be subsumed under G-d\'s rule.   ', 0, 1, 'dmoz_import', '986969', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/judaism' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/history/by-region' LIMIT 1), 'north-america', 'society/history/by-region/north-america', 'North_America', ' ', 0, 1, 'dmoz_import', '971603', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/history/by-region/north-america' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/issues/warfare-and-conflict' LIMIT 1), 'specific-conflicts', 'society/issues/warfare-and-conflict/specific-conflicts', 'Specific_Conflicts', 'This category is for information about specific wars and armed conflicts. ', 0, 1, 'dmoz_import', '983512', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/issues/warfare-and-conflict/specific-conflicts' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/law/services' LIMIT 1), 'lawyers-and-law-firms', 'society/law/services/lawyers-and-law-firms', 'Lawyers_and_Law_Firms', 'This category contains law firms, organized by practice area. Please note that lawyers are regulated by the jurisdictions in which they practice. Please consider confirming that an attorney or firm is licensed, prior to utilizing its services. ', 0, 1, 'dmoz_import', '973530', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/organizations/fraternal' LIMIT 1), 'freemasonry', 'society/organizations/fraternal/freemasonry', 'Freemasonry', 'Freemasonry is a worldwide social and community service organization, emphasizing personal study, self-improvement, and social betterment via individual involvement and philanthropy. This category is meant to list sites established by organizations and individuals relating to the \"Masonic\" fraternity and its related organizations. ', 0, 1, 'dmoz_import', '979835', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/organizations/fraternal/freemasonry' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity' LIMIT 1), 'denominations', 'society/religion-and-spirituality/christianity/denominations', 'Denominations', 'Within this category are listed organizational resources for communities of Christians of the various traditions. Listings are reserved for organized denominations. Single churches, or non-denominational churches, are found in the <A HREF=\"/Society/Religion_and_Spirituality/Christianity/Churches/\">Churches</A> category. ', 0, 1, 'dmoz_import', '989686', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity' LIMIT 1), 'people', 'society/religion-and-spirituality/christianity/people', 'People', 'Located here are sites of interest to all sorts of Christian people:  Men, women, teens, kids, family, and Asian-American.   ', 0, 1, 'dmoz_import', '988123', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/people' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/history/by-region/north-america' LIMIT 1), 'united-states', 'society/history/by-region/north-america/united-states', 'United_States', 'This category concerns the history of the United States of America, from Colonial times through the present day.   ', 0, 1, 'dmoz_import', '971607', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/history/by-region/north-america/united-states' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms' LIMIT 1), 'general-practice', 'society/law/services/lawyers-and-law-firms/general-practice', 'General_Practice', 'General practice and multi practice law firms.  Broken down by state and country.   ', 0, 1, 'dmoz_import', '974551', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms/general-practice' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'anglican', 'society/religion-and-spirituality/christianity/denominations/anglican', 'Anglican', ' ', 0, 1, 'dmoz_import', '989898', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/anglican' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'baptist', 'society/religion-and-spirituality/christianity/denominations/baptist', 'Baptist', 'This category is for all manner of websites related directly to Baptist Christians.  There are over 200 distinct groups of Baptists worldwide, with over 100,000 churches with more than 40,000,000 members. ', 0, 1, 'dmoz_import', '991682', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/baptist' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'catholicism', 'society/religion-and-spirituality/christianity/denominations/catholicism', 'Catholicism', 'I believe in one, holy, catholic, apostolic Church.   This category contains links to various web pages concerning the Catholic Church. Using the common terminology, Catholic here refers to all those churches in communion with the Bishop of Rome, Pope Benedict XVI. Roman Catholics and Eastern Catholics (of all rites) are found here.   For pages concerning Catholic churches not in union with Rome (Polish National Catholic Church, etc.), please see the \"Not in Communion with Rome\" subcategory. ', 0, 1, 'dmoz_import', '993380', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'holiness', 'society/religion-and-spirituality/christianity/denominations/holiness', 'Holiness', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'lutheran', 'society/religion-and-spirituality/christianity/denominations/lutheran', 'Lutheran', 'The Christian Church in western Europe during the early 1500\'s underwent a reformation. The leading exponent of the reformation was <a href=\"/Society/Religion_and_Spirituality/Christianity/Church_History/The_Reformation/Lutheran_Reformation/Luther,_Martin\">Martin Luther</a>. The reformation movement ultimately lead to a complete split between the reformers and the Roman Catholic Church. Those who joined the reformers were later called Protestants as they protested the authority over the Church maintained by the Pope. Those who follow the theology of Martin Luther, the Augsburg Confession and the Book of Concord are called Lutherans. Protestantism as a whole has fractured into many denominations. Those claiming the mantle of Luther have not avoided divisions over doctrinal questions and as a consequence there are a significant number of Lutheran Denominations.  Lutheranism has been the predominant denomination in Northern Germany, and Scandinavia where it is the established (state) church. Lutheran denominations are also prominent in North America.<br> The Lutheran Church began with an emphasis on literacy, scholarship, music, and liturgical worship that continues to this day. ', 0, 1, 'dmoz_import', '990767', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/lutheran' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'methodist', 'society/religion-and-spirituality/christianity/denominations/methodist', 'Methodist', 'Methodism has at its roots one person whose vision, determination and faith inspired fellow seekers to re-assess their lives and renew their relationship with God. John Wesley (1703-1791) challenged the religious assumptions of his day, urging those to whom he preached to \'trust in Christ, Christ alone for salvation\' for the assurance that we are all forgiven through Christ.       When John Wesley was at Oxford University, he was part of a small group of students who met regularly and \'methodically\' for prayer, Bible study and Holy Communion. This earned them the nickname \'The Holy Club\' or \'Methodists\'.       Wesley became a priest in the Church of England, but in 1738 had a spiritual experience that he described as God working in his heart through faith in Christ. He launched a hugely influential preaching ministry and had a flair for organising people into small groups. These he named classes, with locally appointed preachers and leaders, which studied the gospels and prayed together. Wesley\'s new movement became a separate Church which grew rapidly throughout the 18th century and afterwards.   One of the most important distinctions from Calvin and the doctrine of predestination was the doctrine of prevenient grace and its basis in the Arminian view of free will. The United Methodist Church in their book of discipline for 2004 said prevenient grace is \"the divine love that surrounds all humanity and precedes any and all of our conscious impulses. This grace prompts our first wish to please God, our first glimmer of understanding concerning God\'s will, and our \'first slight transient conviction\' of having sinned against God. God\'s grace also awakens in us an earnest longing for deliverance from sin and death and moves us toward repentance and faith.\"  Wesley\'s theology often characterised by the four \"alls\" 1. All need to be saved. 2. All can be saved. 3. All can know they are saved. 4. All can be saved to the full, to the uttermost.   ', 0, 1, 'dmoz_import', '992655', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'presbyterian', 'society/religion-and-spirituality/christianity/denominations/presbyterian', 'Presbyterian', 'Rooted in the Church of Scotland, \"Presbyterian\" describes Christian churches that conform to a governmental structure involving \"presbyters,\" or elders. These elders are a part of a structure that involves regional gatherings of churches, known as \"presbyteries,\" and often regional gatherings of presbyteries, known as \"synods.\" Each denomination known as \"Presbyterian\" varies somewhat in its particular governmental structure, but \"Presbyterian\" describes this congregational connection to a larger body as the primary feature of church government rather than a particular set of beliefs.    Beliefs vary widely among Presbyterian denominations. See their individual categories for more information on beliefs, specific church structure, and individual congregations. ', 0, 1, 'dmoz_import', '991174', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/presbyterian' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/people' LIMIT 1), 'saints', 'society/religion-and-spirituality/christianity/people/saints', 'Saints', 'Information on people who are venerated as saints (or \"blessed\") in more than one Christian tradition. ', 0, 1, 'dmoz_import', '988197', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/people/saints' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms/general-practice' LIMIT 1), 'north-america', 'society/law/services/lawyers-and-law-firms/general-practice/north-america', 'North_America', 'General practice law firms, located in North America. ', 0, 1, 'dmoz_import', '974610', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms/general-practice/north-america' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/baptist' LIMIT 1), 'baptist-groups', 'society/religion-and-spirituality/christianity/denominations/baptist/baptist-groups', 'Baptist_Groups', 'This category contains subcategories for all the various Baptist Groups. ', 0, 1, 'dmoz_import', '991698', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/baptist/baptist-groups' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism' LIMIT 1), 'parishes', 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes', 'Parishes', 'Catholic parishes with web sites. All rites in communion with Rome.   ', 0, 1, 'dmoz_import', '994397', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism' LIMIT 1), 'saints', 'society/religion-and-spirituality/christianity/denominations/catholicism/saints', 'Saints', ' ', 0, 1, 'dmoz_import', '993622', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism/saints' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness' LIMIT 1), 'christian-and-missionary-alliance', 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance', 'Christian And Missionary Alliance', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/lutheran' LIMIT 1), 'congregations', 'society/religion-and-spirituality/christianity/denominations/lutheran/congregations', 'Congregations', 'A gathering into a congregation for worship, fellowship and outreach is the basic formal structure in most Lutheran denominations.   ', 0, 1, 'dmoz_import', '990769', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/lutheran/congregations' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist' LIMIT 1), 'united-methodist', 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist', 'United_Methodist', 'The United Methodist Church is the largest of the churches of the Wesleyan tradition.  Originating in the United States under the leadership of John Wesley and Francis Asbury, it is now growing most rapidly in Africa and has a significant presence throughout the world. The UMC is the successor in the United States to the Methodist Church and the Evangelical United Brethren, which merged in the 1960s.   ', 0, 1, 'dmoz_import', '992689', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/presbyterian' LIMIT 1), 'presbyterian-church-usa', 'society/religion-and-spirituality/christianity/denominations/presbyterian/presbyterian-church-usa', 'Presbyterian_Church_USA', 'The <a href=\"http://www.pcusa.org/\">Presbyterian Church (USA)</a> is the largest Presbyterian denomination in the United States with over 2.5 million members across the country.            Formed in 1983 with the merger of the United Presbyterian Church in the United States of America (\"northern church\") and the Presbyterian Church in the United States (\"southern church\"), the PC(USA) maintains its national offices in <a href=\"/Regional/North_America/United_States/Kentucky/Localities/L/Louisville/\">Louisville, Kentucky</a>. ', 0, 1, 'dmoz_import', '991226', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/presbyterian/presbyterian-church-usa' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms/general-practice/north-america' LIMIT 1), 'united-states', 'society/law/services/lawyers-and-law-firms/general-practice/north-america/united-states', 'United_States', 'This category contains general practice law firms. Please note that lawyers are regulated by the jurisdictions in which they practice. Please consider confirming that an attorney or firm is licensed, prior to utilizing its services. ', 0, 1, 'dmoz_import', '974623', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/law/services/lawyers-and-law-firms/general-practice/north-america/united-states' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes' LIMIT 1), 'north-america', 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america', 'North_America', 'Catholic parishes in North America that have their own web sites.   ', 0, 1, 'dmoz_import', '994432', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance' LIMIT 1), 'camps', 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps', 'Camps', 'Camps, retreats, conference centers, and outdoor recreation facilities affiliated with the C&MA.   ', 0, 1, 'dmoz_import', '995115', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist' LIMIT 1), 'local-churches', 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches', 'Local_Churches', 'This category is for sites about various local congregations. It includes directories.   ', 0, 1, 'dmoz_import', '992690', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america' LIMIT 1), 'united-states', 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america/united-states', 'United_States', ' ', 0, 1, 'dmoz_import', '994444', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/catholicism/parishes/north-america/united-states' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches' LIMIT 1), 'united-states', 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches/united-states', 'United_States', 'This category is for sites belonging to United Methodist congregations in the U.S.A. and which covers *more* than one single church. Local church sites should be listed in the state in which they are based.   ', 0, 1, 'dmoz_import', '992695', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/methodist/united-methodist/local-churches/united-states' LIMIT 1);

-- Sites
INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Alliance Camping International', 'alliance-camping-international', 'http://www.alliancecamping.org/', 'http://www.alliancecamping.org/', 'Directory of camps around the world. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88725', 'Alliance Camping International', 'Directory of camps around the world. ', 'http://www.alliancecamping.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.alliancecamping.org/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Alliance Redwoods Conference Grounds', 'alliance-redwoods-conference-grounds', 'http://allianceredwoods.com/', 'http://allianceredwoods.com/', 'Camp in Occidental, California.  Includes information on retreats, programs, and a virtual tour. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88726', 'Alliance Redwoods Conference Grounds', 'Camp in Occidental, California.  Includes information on retreats, programs, and a virtual tour. ', 'http://allianceredwoods.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://allianceredwoods.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Beulah Beach Camp and Retreat Center', 'beulah-beach-camp-and-retreat-center', 'https://www.beulahbeach.org/', 'https://www.beulahbeach.org/', 'A year round facility on the shores of Lake Erie in north central Ohio. Contains programs, photos, activities, accommodation details, and information request form. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88727', 'Beulah Beach Camp and Retreat Center', 'A year round facility on the shores of Lake Erie in north central Ohio. Contains programs, photos, activities, accommodation details, and information request form. ', 'https://www.beulahbeach.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'https://www.beulahbeach.org/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Big Sandy Camp and Retreat Center', 'big-sandy-camp-and-retreat-center', 'http://www.bigsandycamp.com/', 'http://www.bigsandycamp.com/', 'McGregor, Minnesota.  History, summer camp information, and photos. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88728', 'Big Sandy Camp and Retreat Center', 'McGregor, Minnesota.  History, summer camp information, and photos. ', 'http://www.bigsandycamp.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.bigsandycamp.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Canby Grove Conference Center', 'canby-grove-conference-center', 'https://www.canbygrove.com/', 'https://www.canbygrove.com/', 'Canby, Oregon.  Includes information on facilities, camp sessions, statement of faith, and history. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88729', 'Canby Grove Conference Center', 'Canby, Oregon.  Includes information on facilities, camp sessions, statement of faith, and history. ', 'https://www.canbygrove.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'https://www.canbygrove.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Eagle Bay Camp', 'eagle-bay-camp', 'http://www.eaglebaycamp.com/', 'http://www.eaglebaycamp.com/', 'Located in British Columbia.  Includes information on sessions and a forum. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88730', 'Eagle Bay Camp', 'Located in British Columbia.  Includes information on sessions and a forum. ', 'http://www.eaglebaycamp.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.eaglebaycamp.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Kawkawa Christian Camp and Retreat', 'kawkawa-christian-camp-and-retreat', 'http://www.kawkawa.com/', 'http://www.kawkawa.com/', 'Hope, British Columbia.  Includes a tour, events, and hiring information. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88731', 'Kawkawa Christian Camp and Retreat', 'Hope, British Columbia.  Includes a tour, events, and hiring information. ', 'http://www.kawkawa.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.kawkawa.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Delta Lake Bible Conference Center', 'delta-lake-bible-conference-center', 'http://www.deltalake.org/', 'http://www.deltalake.org/', 'Rome, New York.  Includes events, employment information, and a tour of the facilities. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88732', 'Delta Lake Bible Conference Center', 'Rome, New York.  Includes events, employment information, and a tour of the facilities. ', 'http://www.deltalake.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.deltalake.org/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Mahaffey Camp', 'mahaffey-camp', 'http://www.mahaffeycamp.com/', 'http://www.mahaffeycamp.com/', 'Camp and conference center in Pennsylvania.  Photos, calendar, events, newsletter, and improvement projects. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88733', 'Mahaffey Camp', 'Camp and conference center in Pennsylvania.  Photos, calendar, events, newsletter, and improvement projects. ', 'http://www.mahaffeycamp.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.mahaffeycamp.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Okoboji Lakes Bible & Missionary Conference', 'okoboji-lakes-bible-missionary-conference', 'http://www.okobojiconference.org/', 'http://www.okobojiconference.org/', 'Arnolds Park, Iowa. Site of annual conference in August. Facilities available for rental by individuals and groups at other times. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88734', 'Okoboji Lakes Bible & Missionary Conference', 'Arnolds Park, Iowa. Site of annual conference in August. Facilities available for rental by individuals and groups at other times. ', 'http://www.okobojiconference.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.okobojiconference.org/' LIMIT 1);

COMMIT;
