-- Curlie importer export
-- Generated at 2026-03-21 07:57:30
-- Filters: batch_id=all, branch=Society
-- Export Summary
-- Categories: 7
-- Sites: 10
-- Leaf categories:
--   society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps

START TRANSACTION;

-- Create live import batch record
INSERT INTO import_batches (source_name, source_version, batch_label, notes, status, total_categories, total_sites, started_at, completed_at)
VALUES ('curlie', NULL, 'Curlie export 2026-03-21 07:57:30', 'Generated by standalone Curlie importer', 'completed', 7, 10, NOW(), NOW());
SET @import_batch_id = LAST_INSERT_ID();

-- Categories
INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT NULL, 'society', 'society', 'Society', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society' LIMIT 1), 'religion-and-spirituality', 'society/religion-and-spirituality', 'Religion And Spirituality', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality' LIMIT 1), 'christianity', 'society/religion-and-spirituality/christianity', 'Christianity', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity' LIMIT 1), 'denominations', 'society/religion-and-spirituality/christianity/denominations', 'Denominations', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations' LIMIT 1), 'holiness', 'society/religion-and-spirituality/christianity/denominations/holiness', 'Holiness', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness' LIMIT 1), 'christian-and-missionary-alliance', 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance', 'Christian And Missionary Alliance', NULL, 0, 1, 'dmoz_import', NULL, @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance' LIMIT 1);

INSERT INTO categories (parent_id, slug, path, name, description, sort_order, is_active, source_type, source_key, import_batch_id, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance' LIMIT 1), 'camps', 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps', 'Camps', 'Camps, retreats, conference centers, and outdoor recreation facilities affiliated with the C&MA.   ', 0, 1, 'dmoz_import', '995115', @import_batch_id, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1);

-- Sites
INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Alliance Camping International', 'alliance-camping-international', 'http://www.alliancecamping.org/', 'http://www.alliancecamping.org/', 'Directory of camps around the world. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88725', 'Alliance Camping International', 'Directory of camps around the world. ', 'http://www.alliancecamping.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.alliancecamping.org/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Alliance Redwoods Conference Grounds', 'alliance-redwoods-conference-grounds', 'http://allianceredwoods.com/', 'http://allianceredwoods.com/', 'Camp in Occidental, California.  Includes information on retreats, programs, and a virtual tour. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88726', 'Alliance Redwoods Conference Grounds', 'Camp in Occidental, California.  Includes information on retreats, programs, and a virtual tour. ', 'http://allianceredwoods.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://allianceredwoods.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Beulah Beach Camp and Retreat Center', 'beulah-beach-camp-and-retreat-center', 'https://www.beulahbeach.org/', 'https://www.beulahbeach.org/', 'A year round facility on the shores of Lake Erie in north central Ohio. Contains programs, photos, activities, accommodation details, and information request form. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88727', 'Beulah Beach Camp and Retreat Center', 'A year round facility on the shores of Lake Erie in north central Ohio. Contains programs, photos, activities, accommodation details, and information request form. ', 'https://www.beulahbeach.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'https://www.beulahbeach.org/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Big Sandy Camp and Retreat Center', 'big-sandy-camp-and-retreat-center', 'http://www.bigsandycamp.com/', 'http://www.bigsandycamp.com/', 'McGregor, Minnesota.  History, summer camp information, and photos. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88728', 'Big Sandy Camp and Retreat Center', 'McGregor, Minnesota.  History, summer camp information, and photos. ', 'http://www.bigsandycamp.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.bigsandycamp.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Canby Grove Conference Center', 'canby-grove-conference-center', 'https://www.canbygrove.com/', 'https://www.canbygrove.com/', 'Canby, Oregon.  Includes information on facilities, camp sessions, statement of faith, and history. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88729', 'Canby Grove Conference Center', 'Canby, Oregon.  Includes information on facilities, camp sessions, statement of faith, and history. ', 'https://www.canbygrove.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'https://www.canbygrove.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Eagle Bay Camp', 'eagle-bay-camp', 'http://www.eaglebaycamp.com/', 'http://www.eaglebaycamp.com/', 'Located in British Columbia.  Includes information on sessions and a forum. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88730', 'Eagle Bay Camp', 'Located in British Columbia.  Includes information on sessions and a forum. ', 'http://www.eaglebaycamp.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.eaglebaycamp.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Kawkawa Christian Camp and Retreat', 'kawkawa-christian-camp-and-retreat', 'http://www.kawkawa.com/', 'http://www.kawkawa.com/', 'Hope, British Columbia.  Includes a tour, events, and hiring information. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88731', 'Kawkawa Christian Camp and Retreat', 'Hope, British Columbia.  Includes a tour, events, and hiring information. ', 'http://www.kawkawa.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.kawkawa.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Delta Lake Bible Conference Center', 'delta-lake-bible-conference-center', 'http://www.deltalake.org/', 'http://www.deltalake.org/', 'Rome, New York.  Includes events, employment information, and a tour of the facilities. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88732', 'Delta Lake Bible Conference Center', 'Rome, New York.  Includes events, employment information, and a tour of the facilities. ', 'http://www.deltalake.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.deltalake.org/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Mahaffey Camp', 'mahaffey-camp', 'http://www.mahaffeycamp.com/', 'http://www.mahaffeycamp.com/', 'Camp and conference center in Pennsylvania.  Photos, calendar, events, newsletter, and improvement projects. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88733', 'Mahaffey Camp', 'Camp and conference center in Pennsylvania.  Photos, calendar, events, newsletter, and improvement projects. ', 'http://www.mahaffeycamp.com/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.mahaffeycamp.com/' LIMIT 1);

INSERT INTO sites (category_id, title, slug, url, normalized_url, description, language_code, country_code, status, source_type, source_key, original_title, original_description, original_url, import_batch_id, submitted_by_user_id, is_reviewed, approved_at, is_active, created_at, updated_at)
SELECT (SELECT id FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1), 'Okoboji Lakes Bible & Missionary Conference', 'okoboji-lakes-bible-missionary-conference', 'http://www.okobojiconference.org/', 'http://www.okobojiconference.org/', 'Arnolds Park, Iowa. Site of annual conference in August. Facilities available for rental by individuals and groups at other times. ', NULL, NULL, 'active', 'dmoz_import', 'curlie:995115:88734', 'Okoboji Lakes Bible & Missionary Conference', 'Arnolds Park, Iowa. Site of annual conference in August. Facilities available for rental by individuals and groups at other times. ', 'http://www.okobojiconference.org/', @import_batch_id, NULL, 1, NOW(), 1, NOW(), NOW()
WHERE EXISTS (SELECT 1 FROM categories WHERE path = 'society/religion-and-spirituality/christianity/denominations/holiness/christian-and-missionary-alliance/camps' LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM sites WHERE normalized_url = 'http://www.okobojiconference.org/' LIMIT 1);

COMMIT;
